 "Kenneth E Tomiak"<CBT_Ken@KTomiak.biz>U.S.A. CC: ANYNODE /KTOMIAK   K. Tomiak
                     STANDARD GLOBAL DISCLAIMER--------------------------The aut
hor explicitly disavows any claim whatsoever about thecorrectness or functionali
ty of this program, and disclaims liabilityfor anything and everything bad that
might happen in connection with,before, during, or after using it. I have tried
to make it work right,and I am personally pretty confident that it does, but eve
rybody makesmistakes, so if you use it, you do so at your own risk. Sincerely yo
urs,Kenneth E. Tomiak
